# Generated by Django 2.0.2 on 2018-08-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
