# Generated by Django 2.0.2 on 2018-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='head',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
    ]
